# Generated by Django 4.2.7 on 2026-01-29 14:43

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('taux_horaire', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('statut_actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('derniere_connexion', models.DateTimeField(blank=True, null=True)),
                ('tentatives_connexion_echouees', models.IntegerField(default=0)),
                ('compte_bloque_jusqu', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(choices=[('DIRECTION', 'Direction'), ('CHEF_PROJET', 'Chef de Projet'), ('DEVELOPPEUR', 'Développeur'), ('QA', 'Quality Assurance'), ('FINANCE', 'Finance'), ('SECURITE', 'Sécurité')], max_length=50, unique=True)),
                ('description', models.TextField()),
                ('niveau_hierarchique', models.IntegerField(default=1)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Rôle',
                'verbose_name_plural': 'Rôles',
            },
        ),
        migrations.CreateModel(
            name='StatutProjet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(choices=[('IDEE', 'Idée'), ('AFFECTE', 'Affecté'), ('PLANIFIE', 'Planifié'), ('EN_COURS', 'En cours'), ('SUSPENDU', 'Suspendu'), ('TERMINE', 'Terminé'), ('ARCHIVE', 'Archivé')], max_length=20, unique=True)),
                ('description', models.TextField()),
                ('couleur_affichage', models.CharField(default='#6B7280', max_length=7)),
                ('ordre_affichage', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Statut de Projet',
                'verbose_name_plural': 'Statuts de Projet',
                'ordering': ['ordre_affichage'],
            },
        ),
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField()),
                ('client', models.CharField(max_length=200)),
                ('budget_previsionnel', models.DecimalField(decimal_places=2, max_digits=12)),
                ('devise', models.CharField(default='EUR', max_length=3)),
                ('priorite', models.CharField(choices=[('BASSE', 'Basse'), ('MOYENNE', 'Moyenne'), ('HAUTE', 'Haute'), ('CRITIQUE', 'Critique')], default='MOYENNE', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('commentaires', models.TextField(blank=True)),
                ('createur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projets_crees', to=settings.AUTH_USER_MODEL)),
                ('statut', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projets', to='core.statutprojet')),
            ],
            options={
                'verbose_name': 'Projet',
                'verbose_name_plural': 'Projets',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='ActionAudit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type_action', models.CharField(choices=[('CONNEXION', 'Connexion'), ('DECONNEXION', 'Déconnexion'), ('TENTATIVE_CONNEXION_ECHOUEE', 'Tentative de connexion échouée'), ('CREATION_PROJET', 'Création de projet'), ('MODIFICATION_PROJET', 'Modification de projet'), ('MODIFICATION_BUDGET', 'Modification de budget'), ('CHANGEMENT_STATUT', 'Changement de statut'), ('AFFECTATION_UTILISATEUR', "Affectation d'utilisateur"), ('RETRAIT_UTILISATEUR', "Retrait d'utilisateur"), ('CONSULTATION_AUDIT', "Consultation d'audit"), ('ACCES_REFUSE', 'Accès refusé'), ('ARCHIVAGE_PROJET', 'Archivage de projet')], max_length=50)),
                ('description', models.TextField()),
                ('donnees_avant', models.JSONField(blank=True, null=True)),
                ('donnees_apres', models.JSONField(blank=True, null=True)),
                ('adresse_ip', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('hash_integrite', models.CharField(max_length=64)),
                ('projet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='actions_audit', to='core.projet')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actions_audit', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Action d'Audit",
                'verbose_name_plural': "Actions d'Audit",
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='role_principal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='utilisateurs', to='core.role'),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.CreateModel(
            name='Affectation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('est_responsable_principal', models.BooleanField(default=False)),
                ('pourcentage_temps', models.IntegerField(default=100)),
                ('date_debut', models.DateTimeField(auto_now_add=True)),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affectations', to='core.projet')),
                ('role_sur_projet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.role')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affectations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Affectation',
                'verbose_name_plural': 'Affectations',
                'unique_together': {('utilisateur', 'projet', 'date_fin')},
            },
        ),
    ]
