# Generated by Django 4.2.7 on 2026-01-30 07:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_role_principal'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='affectation',
            new_name='core_affect_utilisa_0517df_idx',
            old_name='core_affectation_user_proj_end_idx',
        ),
        migrations.RenameIndex(
            model_name='affectation',
            new_name='core_affect_projet__16938a_idx',
            old_name='core_affectation_proj_end_idx',
        ),
        migrations.AlterField(
            model_name='actionaudit',
            name='type_action',
            field=models.CharField(choices=[('CONNEXION', 'Connexion'), ('DECONNEXION', 'Déconnexion'), ('TENTATIVE_CONNEXION_ECHOUEE', 'Tentative de connexion échouée'), ('CREATION_PROJET', 'Création de projet'), ('MODIFICATION_PROJET', 'Modification de projet'), ('MODIFICATION_BUDGET', 'Modification de budget'), ('CHANGEMENT_STATUT', 'Changement de statut'), ('AFFECTATION_UTILISATEUR', "Affectation d'utilisateur"), ('RETRAIT_UTILISATEUR', "Retrait d'utilisateur"), ('CONSULTATION_AUDIT', "Consultation d'audit"), ('ACCES_REFUSE', 'Accès refusé'), ('ARCHIVAGE_PROJET', 'Archivage de projet'), ('CREATION_UTILISATEUR', "Création d'utilisateur"), ('MODIFICATION_UTILISATEUR', "Modification d'utilisateur"), ('DESACTIVATION_UTILISATEUR', "Désactivation d'utilisateur"), ('REACTIVATION_UTILISATEUR', "Réactivation d'utilisateur"), ('REINITIALISATION_MOT_PASSE', 'Réinitialisation de mot de passe')], max_length=50),
        ),
        migrations.AlterField(
            model_name='actionaudit',
            name='utilisateur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions_audit', to=settings.AUTH_USER_MODEL),
        ),
    ]
