# Generated by Django 4.2.7 on 2026-01-30 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_fix_audit_user_deletion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionaudit',
            name='type_action',
            field=models.CharField(choices=[('CONNEXION', 'Connexion'), ('DECONNEXION', 'Déconnexion'), ('TENTATIVE_CONNEXION_ECHOUEE', 'Tentative de connexion échouée'), ('CREATION_PROJET', 'Création de projet'), ('MODIFICATION_PROJET', 'Modification de projet'), ('MODIFICATION_BUDGET', 'Modification de budget'), ('CHANGEMENT_STATUT', 'Changement de statut'), ('AFFECTATION_UTILISATEUR', "Affectation d'utilisateur"), ('RETRAIT_UTILISATEUR', "Retrait d'utilisateur"), ('MODIFICATION_ROLE', 'Modification de rôle'), ('CHANGEMENT_RESPONSABLE', 'Changement de responsable'), ('CONSULTATION_AUDIT', "Consultation d'audit"), ('ACCES_REFUSE', 'Accès refusé'), ('ARCHIVAGE_PROJET', 'Archivage de projet'), ('CREATION_UTILISATEUR', "Création d'utilisateur"), ('MODIFICATION_UTILISATEUR', "Modification d'utilisateur"), ('DESACTIVATION_UTILISATEUR', "Désactivation d'utilisateur"), ('REACTIVATION_UTILISATEUR', "Réactivation d'utilisateur"), ('REINITIALISATION_MOT_PASSE', 'Réinitialisation de mot de passe')], max_length=50),
        ),
    ]
