# Generated by Django 4.2.7 on 2026-01-30 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_actionaudit_type_action'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleProjet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(choices=[('RESPONSABLE_PRINCIPAL', 'Responsable Principal'), ('MEMBRE', 'Membre')], max_length=50, unique=True)),
                ('description', models.TextField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Rôle Projet',
                'verbose_name_plural': 'Rôles Projet',
            },
        ),
        migrations.CreateModel(
            name='RoleSysteme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(choices=[('DEVELOPPEUR', 'Développeur'), ('CHEF_PROJET', 'Chef de Projet'), ('QA', 'Quality Assurance'), ('DIRECTION', 'Direction')], max_length=50, unique=True)),
                ('description', models.TextField()),
                ('niveau_hierarchique', models.IntegerField(default=1)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Rôle Système',
                'verbose_name_plural': 'Rôles Système',
                'ordering': ['niveau_hierarchique'],
            },
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'verbose_name': 'Rôle (Deprecated)', 'verbose_name_plural': 'Rôles (Deprecated)'},
        ),
        migrations.AlterField(
            model_name='affectation',
            name='role_sur_projet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.role', verbose_name='Rôle sur le projet (deprecated)'),
        ),
        migrations.AddField(
            model_name='affectation',
            name='role_projet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.roleprojet', verbose_name='Rôle sur le projet'),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='role_systeme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.rolesysteme', verbose_name='Rôle système'),
        ),
    ]
