# Generated by Django 4.2.7 on 2026-01-30 11:52

from django.db import migrations


def migrate_roles_data(apps, schema_editor):
    """Migre les données de l'ancien système de rôles vers le nouveau"""
    
    # Récupérer les modèles
    RoleSysteme = apps.get_model('core', 'RoleSysteme')
    RoleProjet = apps.get_model('core', 'RoleProjet')
    Utilisateur = apps.get_model('core', 'Utilisateur')
    Affectation = apps.get_model('core', 'Affectation')
    Role = apps.get_model('core', 'Role')
    
    # Créer les nouveaux rôles système
    roles_systeme_data = [
        ('DEVELOPPEUR', 'Développeur - Accès aux projets assignés et fonctionnalités de développement', 1),
        ('CHEF_PROJET', 'Chef de projet - Gestion des projets et équipes', 2),
        ('QA', 'Quality Assurance - Tests, validation et contrôle qualité', 1),
        ('DIRECTION', 'Direction - Accès complet et supervision générale', 3),
    ]
    
    for nom, description, niveau in roles_systeme_data:
        RoleSysteme.objects.get_or_create(
            nom=nom,
            defaults={'description': description, 'niveau_hierarchique': niveau}
        )
    
    # Créer les nouveaux rôles projet
    roles_projet_data = [
        ('RESPONSABLE_PRINCIPAL', 'Responsable principal du projet - Gestion complète du projet et de son équipe'),
        ('MEMBRE', 'Membre de l\'équipe projet - Participation aux tâches du projet'),
    ]
    
    for nom, description in roles_projet_data:
        RoleProjet.objects.get_or_create(
            nom=nom,
            defaults={'description': description}
        )
    
    # Migrer les affectations existantes vers les nouveaux rôles projet
    role_membre = RoleProjet.objects.get(nom='MEMBRE')
    role_responsable = RoleProjet.objects.get(nom='RESPONSABLE_PRINCIPAL')
    
    for affectation in Affectation.objects.all():
        if affectation.role_sur_projet:
            # Tous les anciens rôles deviennent "MEMBRE" par défaut
            # Les responsables principaux gardent leur statut via le champ est_responsable_principal
            if affectation.est_responsable_principal:
                affectation.role_projet = role_responsable
            else:
                affectation.role_projet = role_membre
            affectation.save()
    
    # Migrer les utilisateurs vers les rôles système
    # Mapping des anciens rôles vers les nouveaux rôles système
    role_mapping = {
        'DEVELOPPEUR': 'DEVELOPPEUR',
        'CHEF_PROJET': 'CHEF_PROJET', 
        'QA': 'QA',
        'DIRECTION': 'DIRECTION',
        'FINANCE': 'DIRECTION',  # Finance devient Direction
        'SECURITE': 'DIRECTION',  # Sécurité devient Direction
    }
    
    # Pour les utilisateurs existants, essayer de déterminer leur rôle système
    # basé sur leurs affectations actuelles
    for utilisateur in Utilisateur.objects.filter(is_superuser=False):
        if not utilisateur.role_systeme:
            # Essayer de déterminer le rôle basé sur les affectations
            affectations = Affectation.objects.filter(utilisateur=utilisateur, date_fin__isnull=True)
            
            if affectations.exists():
                # Si l'utilisateur est responsable principal sur au moins un projet
                if affectations.filter(est_responsable_principal=True).exists():
                    try:
                        role_chef = RoleSysteme.objects.get(nom='CHEF_PROJET')
                        utilisateur.role_systeme = role_chef
                    except RoleSysteme.DoesNotExist:
                        pass
                else:
                    # Sinon, rôle développeur par défaut
                    try:
                        role_dev = RoleSysteme.objects.get(nom='DEVELOPPEUR')
                        utilisateur.role_systeme = role_dev
                    except RoleSysteme.DoesNotExist:
                        pass
                
                utilisateur.save()


def reverse_migrate_roles_data(apps, schema_editor):
    """Fonction de retour en arrière (optionnelle)"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_roleprojet_rolesysteme_alter_role_options_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_roles_data, reverse_migrate_roles_data),
    ]
