# Generated by Django 4.2.7 on 2026-01-31 15:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20260130_1252'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='utilisateur',
            options={'verbose_name': 'Compte Utilisateur', 'verbose_name_plural': 'Comptes Utilisateur'},
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de création du compte'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='derniere_connexion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Dernière connexion'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='statut_actif',
            field=models.BooleanField(default=True, verbose_name='Compte actif'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='taux_horaire',
            field=models.DecimalField(decimal_places=2, default=0, help_text='DEPRECATED - Utiliser membre.taux_horaire', max_digits=8),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='telephone',
            field=models.CharField(blank=True, help_text='DEPRECATED - Utiliser membre.telephone', max_length=20),
        ),
        migrations.CreateModel(
            name='Membre',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100, verbose_name='Nom de famille')),
                ('prenom', models.CharField(max_length=100, verbose_name='Prénom')),
                ('email_personnel', models.EmailField(max_length=254, unique=True, verbose_name='Email personnel')),
                ('telephone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('telephone_urgence', models.CharField(blank=True, max_length=20, verbose_name="Téléphone d'urgence")),
                ('adresse_ligne1', models.CharField(blank=True, max_length=200, verbose_name='Adresse ligne 1')),
                ('adresse_ligne2', models.CharField(blank=True, max_length=200, verbose_name='Adresse ligne 2')),
                ('ville', models.CharField(blank=True, max_length=100, verbose_name='Ville')),
                ('code_postal', models.CharField(blank=True, max_length=10, verbose_name='Code postal')),
                ('pays', models.CharField(default='France', max_length=100, verbose_name='Pays')),
                ('poste', models.CharField(blank=True, max_length=200, verbose_name='Poste/Fonction')),
                ('departement', models.CharField(blank=True, max_length=100, verbose_name='Département')),
                ('niveau_experience', models.CharField(blank=True, choices=[('JUNIOR', 'Junior (0-2 ans)'), ('INTERMEDIAIRE', 'Intermédiaire (2-5 ans)'), ('SENIOR', 'Senior (5-10 ans)'), ('EXPERT', 'Expert (10+ ans)')], max_length=20, verbose_name="Niveau d'expérience")),
                ('taux_horaire', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Taux horaire')),
                ('devise', models.CharField(default='EUR', max_length=3, verbose_name='Devise')),
                ('competences_techniques', models.TextField(blank=True, help_text='Stack technique, langages, frameworks, outils...', verbose_name='Compétences techniques')),
                ('specialites', models.TextField(blank=True, help_text="Domaines d'expertise, certifications...", verbose_name='Spécialités')),
                ('experiences_cles', models.TextField(blank=True, help_text='Projets marquants, réalisations importantes...', verbose_name='Expériences clés')),
                ('statut', models.CharField(choices=[('ACTIF', 'Actif'), ('INACTIF', 'Inactif'), ('EN_CONGE', 'En congé'), ('SUSPENDU', 'Suspendu')], default='ACTIF', max_length=20, verbose_name='Statut')),
                ('date_embauche', models.DateField(blank=True, null=True, verbose_name="Date d'embauche")),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création du profil')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('notes_rh', models.TextField(blank=True, help_text='Notes internes RH, évaluations, commentaires...', verbose_name='Notes RH')),
                ('createur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='membres_crees', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
            ],
            options={
                'verbose_name': 'Membre',
                'verbose_name_plural': 'Membres',
                'ordering': ['nom', 'prenom'],
            },
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='membre',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compte_utilisateur', to='core.membre', verbose_name='Profil membre'),
        ),
        migrations.AddIndex(
            model_name='membre',
            index=models.Index(fields=['nom', 'prenom'], name='core_membre_nom_396336_idx'),
        ),
        migrations.AddIndex(
            model_name='membre',
            index=models.Index(fields=['email_personnel'], name='core_membre_email_p_f23386_idx'),
        ),
        migrations.AddIndex(
            model_name='membre',
            index=models.Index(fields=['statut'], name='core_membre_statut_35397f_idx'),
        ),
    ]
