# Generated by Django 4.2.7 on 2026-01-31 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_add_membre_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membre',
            name='adresse_ligne1',
        ),
        migrations.RemoveField(
            model_name='membre',
            name='adresse_ligne2',
        ),
        migrations.RemoveField(
            model_name='membre',
            name='code_postal',
        ),
        migrations.RemoveField(
            model_name='membre',
            name='devise',
        ),
        migrations.RemoveField(
            model_name='membre',
            name='experiences_cles',
        ),
        migrations.RemoveField(
            model_name='membre',
            name='notes_rh',
        ),
        migrations.RemoveField(
            model_name='membre',
            name='pays',
        ),
        migrations.RemoveField(
            model_name='membre',
            name='taux_horaire',
        ),
        migrations.RemoveField(
            model_name='membre',
            name='ville',
        ),
        migrations.AddField(
            model_name='membre',
            name='adresse',
            field=models.CharField(default='Adresse à compléter', help_text='Adresse complète (rue, ville)', max_length=300, verbose_name='Adresse complète'),
        ),
    ]
