# Generated by Django 4.2.7 on 2026-01-31 18:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_simplify_membre_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='EtapeProjet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordre', models.IntegerField(help_text='Ordre dans ce projet spécifique')),
                ('statut', models.CharField(choices=[('A_VENIR', 'À venir'), ('EN_COURS', 'En cours'), ('TERMINEE', 'Terminée')], default='A_VENIR', max_length=20)),
                ('date_debut_prevue', models.DateField(blank=True, null=True)),
                ('date_fin_prevue', models.DateField(blank=True, null=True)),
                ('date_debut_reelle', models.DateTimeField(blank=True, null=True)),
                ('date_fin_reelle', models.DateTimeField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('commentaires', models.TextField(blank=True)),
                ('createur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='etapes_creees', to=settings.AUTH_USER_MODEL)),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapes', to='core.projet')),
            ],
            options={
                'verbose_name': 'Étape de Projet',
                'verbose_name_plural': 'Étapes de Projet',
                'ordering': ['projet', 'ordre'],
            },
        ),
        migrations.CreateModel(
            name='ModuleProjet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('couleur', models.CharField(default='#10B981', help_text='Couleur hexadécimale', max_length=7)),
                ('icone_emoji', models.CharField(default='🧩', max_length=10)),
                ('justification_creation_tardive', models.TextField(blank=True, help_text='Justification si créé après la phase de conception')),
                ('createur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='modules_crees', to=settings.AUTH_USER_MODEL)),
                ('etape_creation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='modules_crees', to='core.etapeprojet')),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='core.projet')),
            ],
            options={
                'verbose_name': 'Module de Projet',
                'verbose_name_plural': 'Modules de Projet',
                'ordering': ['projet', 'date_creation'],
            },
        ),
        migrations.CreateModel(
            name='TypeEtape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(choices=[('CONCEPTION', 'Conception'), ('PLANIFICATION', 'Planification'), ('DEVELOPPEMENT', 'Développement'), ('TESTS', 'Tests'), ('DEPLOIEMENT', 'Déploiement'), ('MAINTENANCE', 'Maintenance')], max_length=50, unique=True)),
                ('description', models.TextField()),
                ('ordre_standard', models.IntegerField(help_text='Ordre standard dans le cycle de vie')),
                ('couleur', models.CharField(default='#3B82F6', help_text="Couleur hexadécimale pour l'affichage", max_length=7)),
                ('icone_emoji', models.CharField(default='📋', max_length=10)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': "Type d'Étape",
                'verbose_name_plural': "Types d'Étapes",
                'ordering': ['ordre_standard'],
            },
        ),
        migrations.AlterField(
            model_name='actionaudit',
            name='type_action',
            field=models.CharField(choices=[('CONNEXION', 'Connexion'), ('DECONNEXION', 'Déconnexion'), ('TENTATIVE_CONNEXION_ECHOUEE', 'Tentative de connexion échouée'), ('CREATION_PROJET', 'Création de projet'), ('MODIFICATION_PROJET', 'Modification de projet'), ('MODIFICATION_BUDGET', 'Modification de budget'), ('CHANGEMENT_STATUT', 'Changement de statut'), ('AFFECTATION_UTILISATEUR', "Affectation d'utilisateur"), ('RETRAIT_UTILISATEUR', "Retrait d'utilisateur"), ('MODIFICATION_ROLE', 'Modification de rôle'), ('CHANGEMENT_RESPONSABLE', 'Changement de responsable'), ('CONSULTATION_AUDIT', "Consultation d'audit"), ('ACCES_REFUSE', 'Accès refusé'), ('ARCHIVAGE_PROJET', 'Archivage de projet'), ('CREATION_UTILISATEUR', "Création d'utilisateur"), ('MODIFICATION_UTILISATEUR', "Modification d'utilisateur"), ('DESACTIVATION_UTILISATEUR', "Désactivation d'utilisateur"), ('REACTIVATION_UTILISATEUR', "Réactivation d'utilisateur"), ('REINITIALISATION_MOT_PASSE', 'Réinitialisation de mot de passe'), ('CREATION_ETAPE', "Création d'étape"), ('ACTIVATION_ETAPE', "Activation d'étape"), ('CLOTURE_ETAPE', "Clôture d'étape"), ('CREATION_MODULE', 'Création de module'), ('MODIFICATION_MODULE', 'Modification de module'), ('CREATION_TACHE', 'Création de tâche'), ('MODIFICATION_TACHE', 'Modification de tâche'), ('ASSIGNATION_TACHE', 'Assignation de tâche'), ('COMPLETION_TACHE', 'Completion de tâche'), ('CREATION_MODULE_TARDIVE', 'Création tardive de module')], max_length=50),
        ),
        migrations.AlterField(
            model_name='membre',
            name='adresse',
            field=models.CharField(help_text='Adresse complète (rue, ville)', max_length=300, verbose_name='Adresse complète'),
        ),
        migrations.CreateModel(
            name='TacheModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('duree_estimee', models.DurationField(blank=True, help_text='Durée estimée en heures', null=True)),
                ('date_debut', models.DateField(blank=True, null=True)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('A_FAIRE', 'À faire'), ('EN_COURS', 'En cours'), ('TERMINEE', 'Terminée'), ('BLOQUEE', 'Bloquée')], default='A_FAIRE', max_length=20)),
                ('priorite', models.CharField(choices=[('BASSE', 'Basse'), ('MOYENNE', 'Moyenne'), ('HAUTE', 'Haute'), ('CRITIQUE', 'Critique')], default='MOYENNE', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('commentaires', models.TextField(blank=True)),
                ('raison_blocage', models.TextField(blank=True, help_text='Raison du blocage si statut = BLOQUEE')),
                ('createur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='taches_creees', to=settings.AUTH_USER_MODEL)),
                ('etape_execution', models.ForeignKey(blank=True, help_text='Étape du projet où cette tâche sera exécutée', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.etapeprojet')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taches', to='core.moduleprojet')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taches_assignees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tâche de Module',
                'verbose_name_plural': 'Tâches de Module',
                'ordering': ['module', 'priorite', 'date_creation'],
            },
        ),
        migrations.AddField(
            model_name='etapeprojet',
            name='type_etape',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.typeetape'),
        ),
        migrations.AddConstraint(
            model_name='tachemodule',
            constraint=models.CheckConstraint(check=models.Q(('date_debut__lte', models.F('date_fin'))), name='tache_dates_coherentes'),
        ),
        migrations.AlterUniqueTogether(
            name='moduleprojet',
            unique_together={('projet', 'nom')},
        ),
        migrations.AddConstraint(
            model_name='etapeprojet',
            constraint=models.CheckConstraint(check=models.Q(('date_debut_prevue__lte', models.F('date_fin_prevue'))), name='etape_dates_prevues_coherentes'),
        ),
        migrations.AlterUniqueTogether(
            name='etapeprojet',
            unique_together={('projet', 'type_etape'), ('projet', 'ordre')},
        ),
    ]
