# Generated by Django 4.2.7 on 2026-01-31 19:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_etapeprojet_moduleprojet_typeetape_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TacheEtape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('duree_estimee', models.DurationField(blank=True, help_text='Durée estimée en heures', null=True)),
                ('date_debut', models.DateField(blank=True, null=True)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('A_FAIRE', 'À faire'), ('EN_COURS', 'En cours'), ('TERMINEE', 'Terminée'), ('BLOQUEE', 'Bloquée')], default='A_FAIRE', max_length=20)),
                ('priorite', models.CharField(choices=[('BASSE', 'Basse'), ('MOYENNE', 'Moyenne'), ('HAUTE', 'Haute'), ('CRITIQUE', 'Critique')], default='MOYENNE', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('commentaires', models.TextField(blank=True)),
                ('raison_blocage', models.TextField(blank=True, help_text='Raison du blocage si statut = BLOQUEE')),
                ('createur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='taches_etape_creees', to=settings.AUTH_USER_MODEL)),
                ('etape', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taches_etape', to='core.etapeprojet')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taches_etape_assignees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Tâche d'Étape",
                'verbose_name_plural': "Tâches d'Étape",
                'ordering': ['etape', 'priorite', 'date_creation'],
            },
        ),
        migrations.AddConstraint(
            model_name='tacheetape',
            constraint=models.CheckConstraint(check=models.Q(('date_debut__lte', models.F('date_fin'))), name='tache_etape_dates_coherentes'),
        ),
    ]
