# Generated by Django 4.2.7 on 2026-01-31 19:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_tacheetape_tacheetape_tache_etape_dates_coherentes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etapeprojet',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tacheetape',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
