# Generated by Django 4.2.7 on 2026-02-01 09:00

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_add_activation_automatique_audit'),
    ]

    operations = [
        migrations.AddField(
            model_name='tacheetape',
            name='date_debut_reelle',
            field=models.DateTimeField(blank=True, help_text='Date et heure de début réel de la tâche', null=True),
        ),
        migrations.AddField(
            model_name='tacheetape',
            name='date_fin_reelle',
            field=models.DateTimeField(blank=True, help_text='Date et heure de fin réelle de la tâche', null=True),
        ),
        migrations.AddField(
            model_name='tacheetape',
            name='etiquettes',
            field=models.CharField(blank=True, help_text='Étiquettes séparées par des virgules (ex: urgent,backend,api)', max_length=500),
        ),
        migrations.AddField(
            model_name='tacheetape',
            name='pourcentage_completion',
            field=models.PositiveIntegerField(default=0, help_text='Pourcentage de completion de la tâche (0-100)', validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='tacheetape',
            name='taches_prerequises',
            field=models.ManyToManyField(blank=True, help_text='Tâches qui doivent être terminées avant celle-ci', related_name='taches_dependantes', to='core.tacheetape'),
        ),
        migrations.AddField(
            model_name='tacheetape',
            name='temps_passe',
            field=models.DurationField(blank=True, help_text='Temps réellement passé sur la tâche', null=True),
        ),
        migrations.CreateModel(
            name='StatutTachePersonnalise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Nom du statut personnalisé', max_length=50)),
                ('libelle', models.CharField(help_text='Libellé affiché', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Description du statut')),
                ('couleur', models.CharField(default='#6B7280', help_text="Couleur hex pour l'affichage", max_length=7)),
                ('icone_emoji', models.CharField(default='📋', help_text='Emoji représentant le statut', max_length=10)),
                ('ordre_affichage', models.IntegerField(default=1, help_text="Ordre d'affichage dans les listes")),
                ('est_statut_final', models.BooleanField(default=False, help_text="Indique si c'est un statut de fin")),
                ('permet_modification', models.BooleanField(default=True, help_text='Permet la modification de la tâche')),
                ('transitions_autorisees', models.ManyToManyField(blank=True, help_text='Statuts vers lesquels on peut transitionner', related_name='transitions_depuis', to='core.statuttachepersonnalise')),
                ('type_etape', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuts_taches_personnalises', to='core.typeetape')),
            ],
            options={
                'verbose_name': 'Statut de Tâche Personnalisé',
                'verbose_name_plural': 'Statuts de Tâches Personnalisés',
                'ordering': ['type_etape', 'ordre_affichage'],
                'unique_together': {('type_etape', 'nom')},
            },
        ),
        migrations.CreateModel(
            name='PieceJointeTache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_fichier', models.CharField(help_text='Nom original du fichier', max_length=255)),
                ('fichier', models.FileField(help_text='Fichier attaché', upload_to='taches/pieces_jointes/%Y/%m/')),
                ('taille_fichier', models.PositiveIntegerField(help_text='Taille du fichier en octets')),
                ('type_mime', models.CharField(help_text='Type MIME du fichier', max_length=100)),
                ('date_upload', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, help_text='Description de la pièce jointe')),
                ('version', models.PositiveIntegerField(default=1, help_text='Version du fichier')),
                ('fichier_precedent', models.ForeignKey(blank=True, help_text='Version précédente de ce fichier', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versions_suivantes', to='core.piecejointetache')),
                ('tache', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pieces_jointes', to='core.tacheetape')),
                ('uploade_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploads_taches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pièce Jointe de Tâche',
                'verbose_name_plural': 'Pièces Jointes de Tâches',
                'ordering': ['-date_upload'],
            },
        ),
        migrations.CreateModel(
            name='NotificationTache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_notification', models.CharField(choices=[('ASSIGNATION', 'Assignation de tâche'), ('CHANGEMENT_STATUT', 'Changement de statut'), ('COMMENTAIRE', 'Nouveau commentaire'), ('MENTION', 'Mention dans un commentaire'), ('ECHEANCE', 'Échéance approchante'), ('RETARD', 'Tâche en retard'), ('PIECE_JOINTE', 'Nouvelle pièce jointe')], max_length=20)),
                ('titre', models.CharField(help_text='Titre de la notification', max_length=200)),
                ('message', models.TextField(help_text='Contenu de la notification')),
                ('lue', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_lecture', models.DateTimeField(blank=True, null=True)),
                ('donnees_contexte', models.JSONField(blank=True, help_text='Données contextuelles', null=True)),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications_taches', to=settings.AUTH_USER_MODEL)),
                ('emetteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notifications_emises', to=settings.AUTH_USER_MODEL)),
                ('tache', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core.tacheetape')),
            ],
            options={
                'verbose_name': 'Notification de Tâche',
                'verbose_name_plural': 'Notifications de Tâches',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='HistoriqueTache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_action', models.CharField(choices=[('CREATION', 'Création'), ('MODIFICATION', 'Modification'), ('CHANGEMENT_STATUT', 'Changement de statut'), ('ASSIGNATION', 'Assignation'), ('COMMENTAIRE', 'Ajout de commentaire'), ('SUPPRESSION', 'Suppression')], max_length=20)),
                ('description', models.TextField(help_text="Description de l'action effectuée")),
                ('donnees_avant', models.JSONField(blank=True, help_text='État avant modification', null=True)),
                ('donnees_apres', models.JSONField(blank=True, help_text='État après modification', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('adresse_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('tache', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique', to='core.tacheetape')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actions_taches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historique de Tâche',
                'verbose_name_plural': 'Historiques de Tâches',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='CommentaireTache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField(help_text='Contenu du commentaire')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('modifie', models.BooleanField(default=False)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commentaires_taches', to=settings.AUTH_USER_MODEL)),
                ('mentions', models.ManyToManyField(blank=True, help_text='Utilisateurs mentionnés dans ce commentaire', related_name='mentions_commentaires', to=settings.AUTH_USER_MODEL)),
                ('tache', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaires_tache', to='core.tacheetape')),
            ],
            options={
                'verbose_name': 'Commentaire de Tâche',
                'verbose_name_plural': 'Commentaires de Tâches',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.AddField(
            model_name='tacheetape',
            name='statut_personnalise',
            field=models.ForeignKey(blank=True, help_text="Statut personnalisé selon le type d'étape", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taches_avec_statut', to='core.statuttachepersonnalise'),
        ),
    ]
