# Generated by Django 4.2.7 on 2026-02-03 07:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_add_advanced_task_management'),
    ]

    operations = [
        migrations.AddField(
            model_name='tachemodule',
            name='est_privee',
            field=models.BooleanField(default=True, help_text='Si True, seul le créateur peut voir cette tâche'),
        ),
        migrations.AddField(
            model_name='tachemodule',
            name='visible_par',
            field=models.ManyToManyField(blank=True, help_text='Utilisateurs autorisés à voir cette tâche (en plus du créateur)', related_name='taches_visibles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='actionaudit',
            name='type_action',
            field=models.CharField(choices=[('CONNEXION', 'Connexion'), ('DECONNEXION', 'Déconnexion'), ('TENTATIVE_CONNEXION_ECHOUEE', 'Tentative de connexion échouée'), ('CREATION_PROJET', 'Création de projet'), ('MODIFICATION_PROJET', 'Modification de projet'), ('MODIFICATION_BUDGET', 'Modification de budget'), ('CHANGEMENT_STATUT', 'Changement de statut'), ('AFFECTATION_UTILISATEUR', "Affectation d'utilisateur"), ('RETRAIT_UTILISATEUR', "Retrait d'utilisateur"), ('MODIFICATION_ROLE', 'Modification de rôle'), ('CHANGEMENT_RESPONSABLE', 'Changement de responsable'), ('CONSULTATION_AUDIT', "Consultation d'audit"), ('ACCES_REFUSE', 'Accès refusé'), ('ARCHIVAGE_PROJET', 'Archivage de projet'), ('CREATION_UTILISATEUR', "Création d'utilisateur"), ('MODIFICATION_UTILISATEUR', "Modification d'utilisateur"), ('DESACTIVATION_UTILISATEUR', "Désactivation d'utilisateur"), ('REACTIVATION_UTILISATEUR', "Réactivation d'utilisateur"), ('REINITIALISATION_MOT_PASSE', 'Réinitialisation de mot de passe'), ('CREATION_ETAPE', "Création d'étape"), ('ACTIVATION_ETAPE', "Activation d'étape"), ('ACTIVATION_ETAPE_AUTOMATIQUE', "Activation automatique d'étape"), ('CLOTURE_ETAPE', "Clôture d'étape"), ('CREATION_MODULE', 'Création de module'), ('MODIFICATION_MODULE', 'Modification de module'), ('CREATION_TACHE', 'Création de tâche'), ('MODIFICATION_TACHE', 'Modification de tâche'), ('ASSIGNATION_TACHE', 'Assignation de tâche'), ('COMPLETION_TACHE', 'Completion de tâche'), ('CREATION_MODULE_TARDIVE', 'Création tardive de module'), ('ACTIVATION_MODULES_AUTOMATIQUE', 'Activation automatique des modules'), ('AFFECTATION_MODULE', 'Affectation de module'), ('RETRAIT_MODULE', 'Retrait de module')], max_length=50),
        ),
        migrations.CreateModel(
            name='NotificationEtape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_notification', models.CharField(choices=[('ETAPE_TERMINEE', 'Étape terminée'), ('ETAPE_ACTIVEE', 'Étape activée'), ('MODULES_DISPONIBLES', 'Modules disponibles'), ('RETARD_ETAPE', "Retard d'étape"), ('CHANGEMENT_STATUT', 'Changement de statut')], max_length=20)),
                ('titre', models.CharField(help_text='Titre de la notification', max_length=200)),
                ('message', models.TextField(help_text='Contenu de la notification')),
                ('lue', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_lecture', models.DateTimeField(blank=True, null=True)),
                ('donnees_contexte', models.JSONField(blank=True, help_text='Données contextuelles', null=True)),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications_etapes', to=settings.AUTH_USER_MODEL)),
                ('emetteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notifications_etapes_emises', to=settings.AUTH_USER_MODEL)),
                ('etape', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core.etapeprojet')),
            ],
            options={
                'verbose_name': "Notification d'Étape",
                'verbose_name_plural': "Notifications d'Étapes",
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='AffectationModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_module', models.CharField(choices=[('RESPONSABLE', 'Responsable'), ('CONTRIBUTEUR', 'Contributeur'), ('CONSULTANT', 'Consultant')], default='CONTRIBUTEUR', max_length=20)),
                ('date_affectation', models.DateTimeField(auto_now_add=True)),
                ('date_fin_affectation', models.DateTimeField(blank=True, null=True)),
                ('peut_creer_taches', models.BooleanField(default=True, help_text='Peut créer des tâches dans ce module')),
                ('peut_voir_toutes_taches', models.BooleanField(default=False, help_text='Peut voir toutes les tâches du module')),
                ('affecte_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='affectations_modules_creees', to=settings.AUTH_USER_MODEL)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affectations', to='core.moduleprojet')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules_affectes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Affectation de Module',
                'verbose_name_plural': 'Affectations de Module',
                'ordering': ['module', 'role_module', 'date_affectation'],
                'unique_together': {('module', 'utilisateur', 'date_fin_affectation')},
            },
        ),
    ]
