# Generated by Django 4.2.7 on 2026-02-04 07:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_add_module_affectations'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_notification', models.CharField(choices=[('AFFECTATION_MODULE', 'Affectation au module'), ('RETRAIT_MODULE', 'Retrait du module'), ('NOUVELLE_TACHE', 'Nouvelle tâche assignée'), ('TACHE_TERMINEE', 'Tâche terminée'), ('CHANGEMENT_ROLE', 'Changement de rôle'), ('MODULE_TERMINE', 'Module terminé')], max_length=20)),
                ('titre', models.CharField(help_text='Titre de la notification', max_length=200)),
                ('message', models.TextField(help_text='Contenu de la notification')),
                ('lue', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_lecture', models.DateTimeField(blank=True, null=True)),
                ('donnees_contexte', models.JSONField(blank=True, help_text='Données contextuelles', null=True)),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications_modules', to=settings.AUTH_USER_MODEL)),
                ('emetteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notifications_modules_emises', to=settings.AUTH_USER_MODEL)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core.moduleprojet')),
            ],
            options={
                'verbose_name': 'Notification de Module',
                'verbose_name_plural': 'Notifications de Modules',
                'ordering': ['-date_creation'],
            },
        ),
    ]
