# Generated by Django 4.2.7 on 2026-02-04 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_add_notification_module'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tachemodule',
            options={'ordering': ['module', 'date_creation'], 'verbose_name': 'Tâche de Module', 'verbose_name_plural': 'Tâches de Module'},
        ),
        migrations.RemoveField(
            model_name='tachemodule',
            name='priorite',
        ),
    ]
