# Generated by Django 4.2.7 on 2026-02-05 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_priority_from_tache_module'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tacheetape',
            options={'ordering': ['-date_creation'], 'verbose_name': "Tâche d'Étape", 'verbose_name_plural': "Tâches d'Étape"},
        ),
        migrations.AddField(
            model_name='tacheetape',
            name='ajoutee_apres_cloture',
            field=models.BooleanField(default=False, help_text="Indique si cette tâche a été ajoutée après la clôture de l'étape"),
        ),
        migrations.AddField(
            model_name='tacheetape',
            name='justification_ajout_tardif',
            field=models.TextField(blank=True, help_text="Justification pour l'ajout de cette tâche après clôture de l'étape"),
        ),
        migrations.AlterField(
            model_name='actionaudit',
            name='type_action',
            field=models.CharField(choices=[('CONNEXION', 'Connexion'), ('DECONNEXION', 'Déconnexion'), ('TENTATIVE_CONNEXION_ECHOUEE', 'Tentative de connexion échouée'), ('CREATION_PROJET', 'Création de projet'), ('MODIFICATION_PROJET', 'Modification de projet'), ('MODIFICATION_BUDGET', 'Modification de budget'), ('CHANGEMENT_STATUT', 'Changement de statut'), ('AFFECTATION_UTILISATEUR', "Affectation d'utilisateur"), ('RETRAIT_UTILISATEUR', "Retrait d'utilisateur"), ('MODIFICATION_ROLE', 'Modification de rôle'), ('CHANGEMENT_RESPONSABLE', 'Changement de responsable'), ('CONSULTATION_AUDIT', "Consultation d'audit"), ('CONSULTATION_PROFIL', 'Consultation de profil'), ('MODIFICATION_PROFIL', 'Modification de profil'), ('ACCES_REFUSE', 'Accès refusé'), ('ARCHIVAGE_PROJET', 'Archivage de projet'), ('CREATION_UTILISATEUR', "Création d'utilisateur"), ('MODIFICATION_UTILISATEUR', "Modification d'utilisateur"), ('DESACTIVATION_UTILISATEUR', "Désactivation d'utilisateur"), ('REACTIVATION_UTILISATEUR', "Réactivation d'utilisateur"), ('REINITIALISATION_MOT_PASSE', 'Réinitialisation de mot de passe'), ('CREATION_PROFIL_MEMBRE_ADMIN', 'Création de profil membre par admin'), ('CREATION_ETAPE', "Création d'étape"), ('ACTIVATION_ETAPE', "Activation d'étape"), ('ACTIVATION_ETAPE_AUTOMATIQUE', "Activation automatique d'étape"), ('CLOTURE_ETAPE', "Clôture d'étape"), ('CREATION_MODULE', 'Création de module'), ('MODIFICATION_MODULE', 'Modification de module'), ('CREATION_TACHE', 'Création de tâche'), ('MODIFICATION_TACHE', 'Modification de tâche'), ('ASSIGNATION_TACHE', 'Assignation de tâche'), ('COMPLETION_TACHE', 'Completion de tâche'), ('CREATION_MODULE_TARDIVE', 'Création tardive de module'), ('ACTIVATION_MODULES_AUTOMATIQUE', 'Activation automatique des modules'), ('AFFECTATION_MODULE', 'Affectation de module'), ('RETRAIT_MODULE', 'Retrait de module')], max_length=50),
        ),
        migrations.AlterField(
            model_name='typeetape',
            name='nom',
            field=models.CharField(choices=[('PLANIFICATION', 'Planification'), ('CONCEPTION', 'Conception'), ('DEVELOPPEMENT', 'Développement'), ('TESTS', 'Tests'), ('DEPLOIEMENT', 'Déploiement'), ('MAINTENANCE', 'Maintenance')], max_length=50, unique=True),
        ),
    ]
