# Generated by Django 4.2.7 on 2026-02-05 12:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_add_tache_apres_cloture_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidationTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('est_validee', models.BooleanField(default=False)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('tous_tests_passes', models.BooleanField(default=False)),
                ('aucun_bug_critique', models.BooleanField(default=False)),
                ('commentaires_validation', models.TextField(blank=True)),
                ('conditions_specifiques', models.TextField(blank=True, help_text='Conditions spéciales pour cette validation')),
                ('nb_tests_total', models.IntegerField(default=0)),
                ('nb_tests_passes', models.IntegerField(default=0)),
                ('nb_bugs_critiques', models.IntegerField(default=0)),
                ('nb_bugs_majeurs', models.IntegerField(default=0)),
                ('nb_bugs_mineurs', models.IntegerField(default=0)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('etape', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='validation_test', to='core.etapeprojet')),
                ('validateur', models.ForeignKey(blank=True, help_text='Chef de projet qui a validé', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Validation de Test',
                'verbose_name_plural': 'Validations de Test',
            },
        ),
        migrations.CreateModel(
            name='TacheTest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_test', models.CharField(help_text='Auto-généré: TEST-PROJ-001', max_length=20, unique=True)),
                ('nom', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('type_test', models.CharField(choices=[('FONCTIONNEL', 'Test Fonctionnel'), ('SECURITE', 'Test de Sécurité'), ('INTEGRATION', "Test d'Intégration")], default='FONCTIONNEL', max_length=20)),
                ('priorite', models.CharField(choices=[('CRITIQUE', 'Critique'), ('HAUTE', 'Haute'), ('MOYENNE', 'Moyenne'), ('BASSE', 'Basse')], default='MOYENNE', max_length=20)),
                ('scenario_test', models.TextField(help_text='Étapes détaillées du test')),
                ('resultats_attendus', models.TextField(help_text='Résultats attendus')),
                ('resultats_obtenus', models.TextField(blank=True, help_text="Résultats obtenus lors de l'exécution")),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('EN_COURS', 'En cours'), ('PASSE', 'Passé'), ('ECHEC', 'Échec'), ('BLOQUE', 'Bloqué')], default='EN_ATTENTE', max_length=20)),
                ('date_execution', models.DateTimeField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('assignee_qa', models.ForeignKey(blank=True, help_text='QA responsable du test', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taches_test_assignees', to=settings.AUTH_USER_MODEL)),
                ('createur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='taches_test_creees', to=settings.AUTH_USER_MODEL)),
                ('etape', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taches_test', to='core.etapeprojet')),
                ('executeur', models.ForeignKey(blank=True, help_text='Personne qui a exécuté le test', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tests_executes', to=settings.AUTH_USER_MODEL)),
                ('module_concerne', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.moduleprojet')),
            ],
            options={
                'verbose_name': 'Tâche de Test',
                'verbose_name_plural': 'Tâches de Test',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='BugTest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_bug', models.CharField(help_text='Auto-généré: BUG-PROJ-001', max_length=20, unique=True)),
                ('titre', models.CharField(max_length=200)),
                ('gravite', models.CharField(choices=[('CRITIQUE', 'Critique'), ('MAJEUR', 'Majeur'), ('MINEUR', 'Mineur')], max_length=20)),
                ('type_bug', models.CharField(choices=[('FONCTIONNEL', 'Fonctionnel'), ('SECURITE', 'Sécurité'), ('UI_UX', 'Interface utilisateur'), ('DONNEES', 'Données'), ('AUTRE', 'Autre')], default='FONCTIONNEL', max_length=20)),
                ('description', models.TextField(help_text='Description détaillée du bug')),
                ('etapes_reproduction', models.TextField(help_text='Étapes pour reproduire le bug')),
                ('environnement', models.CharField(blank=True, help_text='Environnement de test', max_length=100)),
                ('statut', models.CharField(choices=[('OUVERT', 'Ouvert'), ('ASSIGNE', 'Assigné'), ('EN_COURS', 'En cours'), ('RESOLU', 'Résolu'), ('FERME', 'Fermé'), ('REJETE', 'Rejeté')], default='OUVERT', max_length=20)),
                ('resolution', models.TextField(blank=True, help_text='Description de la résolution')),
                ('date_resolution', models.DateTimeField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('assignee_dev', models.ForeignKey(blank=True, help_text='Développeur assigné pour la correction', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bugs_assignes', to=settings.AUTH_USER_MODEL)),
                ('module_concerne', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.moduleprojet')),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bugs_test', to='core.projet')),
                ('rapporteur', models.ForeignKey(help_text='QA qui a rapporté le bug', on_delete=django.db.models.deletion.PROTECT, related_name='bugs_rapportes', to=settings.AUTH_USER_MODEL)),
                ('tache_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bugs', to='core.tachetest')),
            ],
            options={
                'verbose_name': 'Bug de Test',
                'verbose_name_plural': 'Bugs de Test',
                'ordering': ['-date_creation'],
            },
        ),
    ]
