# Generated by Django 4.2.7 on 2026-02-05 13:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_add_systeme_tests_v1'),
    ]

    operations = [
        migrations.CreateModel(
            name='CasTest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_cas', models.CharField(help_text='Auto-généré: AUTH-001, AUTH-002, etc.', max_length=30)),
                ('nom', models.CharField(help_text='Ex: Connexion avec email valide', max_length=200)),
                ('description', models.TextField(help_text='Description détaillée du cas de test')),
                ('priorite', models.CharField(choices=[('CRITIQUE', 'Critique'), ('HAUTE', 'Haute'), ('MOYENNE', 'Moyenne'), ('BASSE', 'Basse')], default='MOYENNE', max_length=20)),
                ('donnees_entree', models.TextField(blank=True, help_text="Données d'entrée du test")),
                ('preconditions', models.TextField(blank=True, help_text='Conditions préalables à remplir')),
                ('etapes_execution', models.TextField(help_text='Étapes détaillées pour exécuter ce cas')),
                ('resultats_attendus', models.TextField(help_text='Résultats attendus pour ce cas spécifique')),
                ('resultats_obtenus', models.TextField(blank=True, help_text="Résultats obtenus lors de l'exécution")),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('EN_COURS', 'En cours'), ('PASSE', 'Passé'), ('ECHEC', 'Échec'), ('BLOQUE', 'Bloqué')], default='EN_ATTENTE', max_length=20)),
                ('date_execution', models.DateTimeField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('ordre', models.PositiveIntegerField(default=1)),
                ('createur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cas_tests_crees', to=settings.AUTH_USER_MODEL)),
                ('executeur', models.ForeignKey(blank=True, help_text='QA qui a exécuté ce cas', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cas_tests_executes', to=settings.AUTH_USER_MODEL)),
                ('tache_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cas_tests', to='core.tachetest')),
            ],
            options={
                'verbose_name': 'Cas de test',
                'verbose_name_plural': 'Cas de tests',
                'ordering': ['ordre', 'date_creation'],
                'unique_together': {('tache_test', 'numero_cas')},
            },
        ),
        migrations.AddField(
            model_name='notificationetape',
            name='cas_test',
            field=models.ForeignKey(blank=True, help_text='Cas de test qui a généré ce bug', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commentairetache_cas_tests', to='core.castest'),
        ),
        migrations.AddField(
            model_name='tacheetape',
            name='cas_test',
            field=models.ForeignKey(blank=True, help_text='Cas de test qui a généré ce bug', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rolesysteme_cas_tests', to='core.castest'),
        ),
        migrations.AddField(
            model_name='tachetest',
            name='cas_test',
            field=models.ForeignKey(blank=True, help_text='Cas de test qui a généré ce bug', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificationmodule_cas_tests', to='core.castest'),
        ),
    ]
