# Generated by Django 4.2.7 on 2026-02-12 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_add_cas_test_passe_notification'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='projet',
            name='core_projet_date_fin_idx',
        ),
        migrations.RenameIndex(
            model_name='notificationprojet',
            new_name='core_notifi_destina_af094b_idx',
            old_name='core_notifi_destina_idx',
        ),
        migrations.RenameIndex(
            model_name='notificationprojet',
            new_name='core_notifi_projet__334f21_idx',
            old_name='core_notifi_projet_idx',
        ),
        migrations.AlterUniqueTogether(
            name='castest',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='castest',
            name='tache_etape',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cas_tests', to='core.tacheetape'),
        ),
        migrations.AlterField(
            model_name='tacheetape',
            name='statut',
            field=models.CharField(choices=[('A_FAIRE', 'À faire'), ('EN_COURS', 'En cours'), ('TERMINEE', 'Terminée'), ('BLOQUEE', 'Bloquée'), ('ECHEC', 'Échec')], default='A_FAIRE', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='castest',
            unique_together={('tache_etape', 'numero_cas')},
        ),
        migrations.RemoveField(
            model_name='castest',
            name='tache_test',
        ),
    ]
