# Generated by Django 4.2.7 on 2026-02-12 10:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_add_assignes_a_manytomany'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='ticketmaintenance',
            new_name='core_ticket_numero__8aaf09_idx',
            old_name='core_ticket_numero_idx',
        ),
        migrations.RenameIndex(
            model_name='ticketmaintenance',
            new_name='core_ticket_statut_c4e803_idx',
            old_name='core_ticket_statut_idx',
        ),
        migrations.RenameIndex(
            model_name='ticketmaintenance',
            new_name='core_ticket_priorit_ae9c33_idx',
            old_name='core_ticket_priorite_idx',
        ),
        migrations.RenameIndex(
            model_name='ticketmaintenance',
            new_name='core_ticket_date_cr_2d2e68_idx',
            old_name='core_ticket_date_idx',
        ),
        migrations.AlterField(
            model_name='notificationprojet',
            name='type_notification',
            field=models.CharField(choices=[('AFFECTATION_RESPONSABLE', 'Affectation comme responsable'), ('AJOUT_EQUIPE', "Ajout à l'équipe du projet"), ('PROJET_DEMARRE', 'Projet démarré'), ('ALERTE_FIN_PROJET', 'Alerte fin de projet (J-7)'), ('PROJET_TERMINE', 'Projet terminé'), ('PROJET_SUSPENDU', 'Projet suspendu'), ('CHANGEMENT_ECHEANCE', "Changement d'échéance"), ('ASSIGNATION_TICKET_MAINTENANCE', 'Assignation ticket de maintenance')], max_length=30),
        ),
        migrations.AlterField(
            model_name='ticketmaintenance',
            name='assigne_a',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_assignes', to=settings.AUTH_USER_MODEL, verbose_name='Assigné à (ancien)'),
        ),
        migrations.AlterField(
            model_name='ticketmaintenance',
            name='contrat_garantie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='core.contratgarantie', verbose_name='Contrat de garantie'),
        ),
        migrations.AlterField(
            model_name='ticketmaintenance',
            name='cree_par',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_crees', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AlterField(
            model_name='ticketmaintenance',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='ticketmaintenance',
            name='date_fermeture',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de fermeture'),
        ),
        migrations.AlterField(
            model_name='ticketmaintenance',
            name='date_resolution',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de résolution'),
        ),
        migrations.AlterField(
            model_name='ticketmaintenance',
            name='est_payant',
            field=models.BooleanField(default=False, help_text='True si hors garantie ou garantie inactive', verbose_name='Intervention payante (ancien)'),
        ),
        migrations.AlterField(
            model_name='ticketmaintenance',
            name='origine',
            field=models.CharField(choices=[('CLIENT', 'Client'), ('MONITORING', 'Monitoring'), ('INTERNE', 'Interne')], default='CLIENT', max_length=20),
        ),
        migrations.AlterField(
            model_name='ticketmaintenance',
            name='raison_rejet',
            field=models.TextField(blank=True, help_text="Pourquoi le ticket n'est pas couvert", verbose_name='Raison hors garantie'),
        ),
        migrations.AlterField(
            model_name='ticketmaintenance',
            name='titre',
            field=models.CharField(max_length=200, verbose_name='Titre'),
        ),
    ]
