# Generated by Django 4.2.7 on 2026-02-12 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_add_assignation_ticket_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationprojet',
            name='type_notification',
            field=models.CharField(choices=[('AFFECTATION_RESPONSABLE', 'Affectation comme responsable'), ('AJOUT_EQUIPE', "Ajout à l'équipe du projet"), ('PROJET_DEMARRE', 'Projet démarré'), ('ALERTE_FIN_PROJET', 'Alerte fin de projet (J-7)'), ('PROJET_TERMINE', 'Projet terminé'), ('PROJET_SUSPENDU', 'Projet suspendu'), ('CHANGEMENT_ECHEANCE', "Changement d'échéance"), ('ASSIGNATION_TICKET_MAINTENANCE', 'Assignation ticket de maintenance'), ('TICKET_RESOLU', 'Ticket de maintenance résolu')], max_length=30),
        ),
    ]
