# Generated by Django 4.2.7 on 2026-02-13 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_add_account_activation_system'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='accountactivationlog',
            new_name='core_accoun_user_id_70ef7b_idx',
            old_name='core_accoun_user_id_created_at_idx',
        ),
        migrations.RenameIndex(
            model_name='accountactivationlog',
            new_name='core_accoun_action_699d13_idx',
            old_name='core_accoun_action_created_at_idx',
        ),
        migrations.RenameIndex(
            model_name='accountactivationtoken',
            new_name='core_accoun_user_id_1e648b_idx',
            old_name='core_accoun_user_id_is_used_expires_idx',
        ),
        migrations.RenameIndex(
            model_name='accountactivationtoken',
            new_name='core_accoun_token_h_c0535f_idx',
            old_name='core_accoun_token_hash_idx',
        ),
        migrations.RenameIndex(
            model_name='accountactivationtoken',
            new_name='core_accoun_expires_47d3dd_idx',
            old_name='core_accoun_expires_at_idx',
        ),
        migrations.RenameIndex(
            model_name='alerteprojet',
            new_name='core_alerte_destina_a75019_idx',
            old_name='core_alerte_destina_idx',
        ),
        migrations.RenameIndex(
            model_name='alerteprojet',
            new_name='core_alerte_projet__8cf3b9_idx',
            old_name='core_alerte_projet_idx',
        ),
        migrations.RenameIndex(
            model_name='alerteprojet',
            new_name='core_alerte_type_al_e0484f_idx',
            old_name='core_alerte_type_al_idx',
        ),
    ]
