# Generated by Django 4.2.7 on 2026-02-16 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_add_changement_statut_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionaudit',
            name='projet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions_audit', to='core.projet'),
        ),
    ]
