# Generated by Django 4.2.7 on 2026-02-16 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_add_ligne_budget'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='lignebudget',
            new_name='core_ligneb_projet__35ca9e_idx',
            old_name='core_ligneb_projet__idx',
        ),
        migrations.RenameIndex(
            model_name='lignebudget',
            new_name='core_ligneb_date_aj_cf6ffe_idx',
            old_name='core_ligneb_date_aj_idx',
        ),
    ]
