# Generated by Django 4.2.7 on 2026-02-16 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_rename_core_ligneb_projet__idx_core_ligneb_projet__35ca9e_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lignebudget',
            name='description',
            field=models.CharField(max_length=255, verbose_name='Nom de la dépense'),
        ),
    ]
